% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt]{report}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
    \setmainfont[]{Times New Roman}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[top=20mm,left=15mm,right=15mm,bottom=20mm]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{anyfontsize}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={LLM Performance in Clinical Question Answering: Results},
  pdfauthor={Christoph Reich},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{LLM Performance in Clinical Question Answering: Results}
\author{Christoph Reich}
\date{2025-06-17}

\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\chapter{Results}\label{results}

\section{1. Descriptive Statistics}\label{descriptive-statistics}

\subsection{1.1 Response
Characteristics}\label{response-characteristics}

We calculate and present readability metrics for medical text responses
using the \textbf{quanteda} and \textbf{quanteda.textstats} packages. We
will compute the following indices:

\begin{itemize}
\tightlist
\item
  \textbf{Flesch Reading Ease}
\item
  \textbf{Flesch-Kincaid Grade Level}
\item
  \textbf{Gunning Fog Index}
\item
  \textbf{SMOG Index}
\item
  \textbf{Coleman-Liau Index}
\item
  \textbf{Automated Readability Index (ARI)}
\end{itemize}

We will present descriptive statistics and visualizations in two ways:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Per model}
\item
  \textbf{Per model and category}
\end{enumerate}

\subsubsection{A) Flesch-Based Readability
Formulas}\label{a-flesch-based-readability-formulas}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Flesch Reading Ease (FRE)}

  \begin{itemize}
  \item
    \textbf{Formula}:
    \texttt{206.835\ –\ (1.015\ ×\ ASL)\ –\ (84.6\ ×\ ASW)}

    \begin{itemize}
    \tightlist
    \item
      \emph{ASL}: Average Sentence Length (words per sentence)
    \item
      \emph{ASW}: Average Syllables per Word
    \end{itemize}
  \item
    \textbf{Output}: Score ranging from 0 to 100; higher scores indicate
    easier readability.
  \item
    \textbf{Interpretation}:

    \begin{itemize}
    \tightlist
    \item
      90--100: Very easy (understood by 11-year-olds)
    \item
      60--70: Standard (13--15-year-olds)
    \item
      30--50: Difficult (college level)
    \end{itemize}
  \item
    \textbf{Usage}: Provides a general sense of text readability but
    requires a conversion table to relate scores to grade levels.
    ({[}en.wikipedia.org{]}{[}1{]}, {[}readable.com{]}{[}2{]})
  \end{itemize}
\item
  \textbf{Flesch-Kincaid Grade Level (FKGL)}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Formula}: \texttt{0.39\ ×\ ASL\ +\ 11.8\ ×\ ASW\ –\ 15.59}
  \item
    \textbf{Output}: U.S. school grade level; for example, a score of
    8.5 corresponds to an 8th-grade reading level.
  \item
    \textbf{Usage}: Directly indicates the education level required to
    comprehend the text, making it practical for assessing materials
    intended for specific audiences. ({[}de.wikipedia.org{]}{[}3{]},
    {[}nira.com{]}{[}4{]})
  \end{itemize}
\item
  \textbf{Flesch.PSK (Powers-Sumner-Kearl Variation)}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Formula}:
    \texttt{(0.0778\ ×\ ASL)\ +\ (4.55\ ×\ ASW)\ –\ 2.2029}
  \item
    \textbf{Usage}: A less commonly used variation; not widely adopted
    in current readability assessments.
  \end{itemize}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

In medical and health-related fields, ensuring that patient education
materials are accessible is crucial. Both FRE and FKGL are commonly used
to assess the readability of such materials. However, FKGL is often
preferred because it provides a direct correlation to U.S. grade levels,
simplifying the assessment of whether materials are appropriate for the
target audience.
(\href{https://journals.lww.com/edhe/fulltext/2017/30010/assessing_reading_levels_of_health_information_.15.aspx}{journals.lww.com})

For instance, a study analyzing patient information sheets found that
the mean FKGL was 11.4, indicating that the materials were written at a
level suitable for individuals with at least an 11th-grade education.
(\href{https://pubmed.ncbi.nlm.nih.gov/36131293/}{pubmed.ncbi.nlm.nih.gov})

\begin{itemize}
\tightlist
\item
  \textbf{Use Flesch-Kincaid Grade Level (FKGL)} when you need a
  straightforward indication of the education level required to
  understand the text. This is particularly useful in medical contexts,
  where materials should be tailored to the patient's reading
  ability.({[}en.wikipedia.org{]}{[}7{]})
\item
  \textbf{Use Flesch Reading Ease (FRE)} if you prefer a score that
  reflects the overall readability on a 100-point scale. This can be
  helpful for comparing the readability of different texts or versions
  of the same text.
\end{itemize}

\begin{table}
\caption*{
{\large Table 1: Readability Metrics by Model}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrllllll}
\toprule
model & n\_responses & Flesch Ease & Flesch K-G & Gunning Fog & SMOG & Coleman-Liau & ARI \\ 
\midrule\addlinespace[2.5pt]
Anthropic & 50 & -34.8 ± 57.1 & 35.2 ± 20.5 & 39.6 ± 21.3 & 28.0 ± 9.8 & 19.6 ± 2.6 & 41.7 ± 26.0 \\ 
Deepseek & 50 & 26.6 ± 13.9 & 14.6 ± 3.0 & 18.1 ± 3.4 & 15.8 ± 2.5 & 15.7 ± 1.9 & 15.2 ± 3.4 \\ 
Google & 50 & 38.2 ± 11.2 & 11.9 ± 1.8 & 15.4 ± 2.2 & 13.8 ± 1.5 & 13.9 ± 1.9 & 12.0 ± 1.9 \\ 
Openai & 50 & 27.7 ± 12.0 & 15.0 ± 3.1 & 18.8 ± 3.2 & 16.3 ± 2.3 & 15.3 ± 1.7 & 16.0 ± 3.9 \\ 
Perplexity & 50 & 9.4 ± 27.3 & 21.1 ± 9.9 & 25.0 ± 10.2 & 20.0 ± 4.5 & 16.7 ± 2.1 & 23.7 ± 12.8 \\ 
Xai & 50 & 32.4 ± 11.6 & 14.4 ± 2.6 & 17.9 ± 3.0 & 15.8 ± 2.1 & 14.4 ± 1.6 & 15.2 ± 3.0 \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/density-plot-flesch-by-model-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/violin-plot-flesch-model-1.pdf}}

\begin{table}
\caption*{
{\large Table 2: Readability Metrics by Category and Model}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrllllll}
\toprule
model & n\_responses & Flesch Ease & Flesch K-G & Gunning Fog & SMOG & Coleman-Liau & ARI \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{l}{Disease Understanding and Diagnosis} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Anthropic & 14 & -32.6 ± 65.7 & 35.7 ± 22.4 & 40.1 ± 23.2 & 27.7 ± 11.3 & 18.7 ± 3.1 & 42.7 ± 28.3 \\ 
Deepseek & 14 & 25.7 ± 16.9 & 14.9 ± 3.8 & 18.3 ± 4.3 & 15.9 ± 3.1 & 16.0 ± 2.5 & 15.8 ± 4.6 \\ 
Google & 14 & 39.2 ± 15.5 & 12.1 ± 2.2 & 15.4 ± 2.8 & 13.8 ± 1.9 & 13.8 ± 2.6 & 12.3 ± 2.2 \\ 
Openai & 14 & 26.4 ± 16.5 & 15.7 ± 4.0 & 19.5 ± 4.3 & 16.8 ± 3.0 & 15.3 ± 2.2 & 16.9 ± 4.9 \\ 
Perplexity & 14 & 20.0 ± 16.9 & 18.4 ± 3.8 & 22.2 ± 4.3 & 18.4 ± 3.1 & 15.4 ± 2.3 & 20.3 ± 4.3 \\ 
Xai & 14 & 32.0 ± 15.1 & 14.4 ± 2.9 & 17.9 ± 3.3 & 15.7 ± 2.3 & 14.5 ± 2.2 & 15.1 ± 3.3 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{l}{Treatment and Management} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Anthropic & 27 & -25.4 ± 46.9 & 31.0 ± 17.3 & 35.4 ± 18.1 & 26.3 ± 7.9 & 19.9 ± 2.2 & 36.3 ± 22.0 \\ 
Deepseek & 27 & 26.3 ± 13.9 & 14.7 ± 3.0 & 18.3 ± 3.2 & 16.0 ± 2.3 & 15.7 ± 1.7 & 15.3 ± 3.0 \\ 
Google & 27 & 36.9 ± 8.4 & 12.1 ± 1.4 & 15.7 ± 1.7 & 14.1 ± 1.2 & 14.2 ± 1.4 & 12.1 ± 1.6 \\ 
Openai & 27 & 28.0 ± 10.1 & 14.6 ± 2.7 & 18.4 ± 2.6 & 16.1 ± 1.9 & 15.5 ± 1.4 & 15.5 ± 3.5 \\ 
Perplexity & 27 & 11.0 ± 16.2 & 19.7 ± 5.1 & 23.6 ± 5.1 & 19.5 ± 3.2 & 17.3 ± 1.9 & 21.9 ± 6.4 \\ 
Xai & 27 & 32.7 ± 10.7 & 14.5 ± 2.8 & 18.0 ± 3.1 & 15.9 ± 2.2 & 14.3 ± 1.3 & 15.4 ± 3.3 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{l}{Lifestyle \& Daily Activity} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Anthropic & 9 & -66.6 ± 65.8 & 46.8 ± 23.7 & 51.7 ± 24.7 & 33.7 ± 11.2 & 20.2 ± 2.5 & 56.6 ± 30.3 \\ 
Deepseek & 9 & 28.6 ± 9.0 & 13.8 ± 1.9 & 17.2 ± 2.5 & 15.1 ± 1.8 & 15.5 ± 1.6 & 14.2 ± 2.4 \\ 
Google & 9 & 40.6 ± 11.8 & 11.2 ± 2.0 & 14.5 ± 2.4 & 13.2 ± 1.7 & 13.4 ± 1.8 & 10.9 ± 2.0 \\ 
Openai & 9 & 28.9 ± 9.9 & 15.1 ± 2.6 & 18.9 ± 2.8 & 16.3 ± 2.0 & 14.7 ± 1.6 & 15.9 ± 3.6 \\ 
Perplexity & 9 & -12.2 ± 50.2 & 29.5 ± 19.9 & 33.8 ± 20.5 & 23.6 ± 7.5 & 16.9 ± 1.2 & 34.6 ± 25.9 \\ 
Xai & 9 & 32.2 ± 8.5 & 14.1 ± 1.6 & 17.6 ± 2.4 & 15.6 ± 1.8 & 14.4 ± 1.2 & 14.7 ± 1.6 \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/density-plot-flesch-by-model-category-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/violin-plot-flesch-model-category-1.pdf}}

\subsubsection{B) Word Count}\label{b-word-count}

\begin{table}
\caption*{
{\large Table 3: Response Characteristics by Model (Word Count)}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrl}
\toprule
model & Response Count & Word Count \\ 
\midrule\addlinespace[2.5pt]
anthropic & 50 & 226.9 ± 38.9 \\ 
deepseek & 50 & 299.5 ± 57.8 \\ 
google & 50 & 668.7 ± 116.1 \\ 
openai & 50 & 475.8 ± 133.4 \\ 
perplexity & 50 & 346.4 ± 63.4 \\ 
xai & 50 & 671.2 ± 202.3 \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/wc-violin-model-1.pdf}}

\subsection{1.2 Overall Performance by
Model}\label{overall-performance-by-model}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/overall-model-performance-plot-1.pdf}}

\subsubsection{1.2.1 Model Preferred by
Rater}\label{model-preferred-by-rater}

\begin{table}
\caption*{
{\large Overall Model Preferences Across All Raters}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrr}
\toprule
Preferred Model & Count & Percentage (\%) \\ 
\midrule\addlinespace[2.5pt]
Google & 131 & 43.7 \\ 
Xai & 91 & 30.3 \\ 
Openai & 35 & 11.7 \\ 
Anthropic & 22 & 7.3 \\ 
Perplexity & 12 & 4.0 \\ 
Deepseek & 9 & 3.0 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{table}
\caption*{
{\large Reasons for Model Preference}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrr}
\toprule
Reason & Count & Percentage (\%) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Anthropic}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Easier to understand (lay language) & 8 & 36.4 \\ 
Best reflects clinical practice & 7 & 31.8 \\ 
Clearer explanation & 3 & 13.6 \\ 
More empathetic tone & 2 & 9.1 \\ 
Safest advice & 2 & 9.1 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Deepseek}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Clearer explanation & 3 & 33.3 \\ 
Easier to understand (lay language) & 2 & 22.2 \\ 
Safest advice & 2 & 22.2 \\ 
Best reflects clinical practice & 1 & 11.1 \\ 
More complete content & 1 & 11.1 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Google}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Clearer explanation & 46 & 35.1 \\ 
More complete content & 41 & 31.3 \\ 
Best reflects clinical practice & 18 & 13.7 \\ 
Safest advice & 11 & 8.4 \\ 
Easier to understand (lay language) & 9 & 6.9 \\ 
More empathetic tone & 6 & 4.6 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Openai}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Easier to understand (lay language) & 11 & 31.4 \\ 
Clearer explanation & 9 & 25.7 \\ 
More empathetic tone & 5 & 14.3 \\ 
Safest advice & 4 & 11.4 \\ 
Best reflects clinical practice & 3 & 8.6 \\ 
More complete content & 3 & 8.6 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Perplexity}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Easier to understand (lay language) & 4 & 33.3 \\ 
Best reflects clinical practice & 2 & 16.7 \\ 
Clearer explanation & 2 & 16.7 \\ 
More complete content & 2 & 16.7 \\ 
More empathetic tone & 1 & 8.3 \\ 
Safest advice & 1 & 8.3 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{{\bfseries Xai}} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Easier to understand (lay language) & 29 & 31.9 \\ 
Clearer explanation & 24 & 26.4 \\ 
More complete content & 19 & 20.9 \\ 
Best reflects clinical practice & 7 & 7.7 \\ 
Safest advice & 7 & 7.7 \\ 
More empathetic tone & 5 & 5.5 \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/barplot-rater-preferences-overall-1.pdf}}

\begin{table}
\caption*{
{\large Model Preferences by Individual Rater}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrr}
\toprule
Preferred Model & Count & Percentage (\%) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Expert 1} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 16 & 32 \\ 
Anthropic & 12 & 24 \\ 
Xai & 8 & 16 \\ 
Openai & 7 & 14 \\ 
Perplexity & 5 & 10 \\ 
Deepseek & 2 & 4 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Expert 2} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 31 & 62 \\ 
Xai & 17 & 34 \\ 
Deepseek & 2 & 4 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Expert 3} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Xai & 23 & 46 \\ 
Openai & 13 & 26 \\ 
Anthropic & 6 & 12 \\ 
Deepseek & 4 & 8 \\ 
Google & 3 & 6 \\ 
Perplexity & 1 & 2 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Student 1} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 21 & 42 \\ 
Xai & 19 & 38 \\ 
Openai & 4 & 8 \\ 
Perplexity & 4 & 8 \\ 
Anthropic & 2 & 4 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Student 2} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 29 & 58 \\ 
Xai & 13 & 26 \\ 
Openai & 7 & 14 \\ 
Anthropic & 1 & 2 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Student 3} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 31 & 62 \\ 
Xai & 11 & 22 \\ 
Openai & 4 & 8 \\ 
Perplexity & 2 & 4 \\ 
Anthropic & 1 & 2 \\ 
Deepseek & 1 & 2 \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/barplot-preferences-by-rater-expert-student-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/barplot-preferences-expert-student-facetwrap-category-1.pdf}}

\begin{table}
\caption*{
{\large Model Preferences by Rater Type and Category}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}crr}
\toprule
Preferred Model & Count & Percentage (\%) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Disease Understanding and Diagnosis - Expert} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Xai & 22 & 52.4 \\ 
Google & 8 & 19.0 \\ 
Anthropic & 3 & 7.1 \\ 
Deepseek & 3 & 7.1 \\ 
Openai & 3 & 7.1 \\ 
Perplexity & 3 & 7.1 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Disease Understanding and Diagnosis - Student} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Xai & 20 & 47.6 \\ 
Google & 15 & 35.7 \\ 
Openai & 5 & 11.9 \\ 
Perplexity & 2 & 4.8 \\ 
Anthropic & 0 & 0.0 \\ 
Deepseek & 0 & 0.0 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Lifestyle \& Daily Activity - Expert} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 8 & 29.6 \\ 
Xai & 7 & 25.9 \\ 
Openai & 5 & 18.5 \\ 
Anthropic & 4 & 14.8 \\ 
Perplexity & 2 & 7.4 \\ 
Deepseek & 1 & 3.7 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Lifestyle \& Daily Activity - Student} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 14 & 51.9 \\ 
Xai & 8 & 29.6 \\ 
Openai & 4 & 14.8 \\ 
Perplexity & 1 & 3.7 \\ 
Anthropic & 0 & 0.0 \\ 
Deepseek & 0 & 0.0 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Treatment and Management - Expert} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 34 & 42.0 \\ 
Xai & 19 & 23.5 \\ 
Openai & 12 & 14.8 \\ 
Anthropic & 11 & 13.6 \\ 
Deepseek & 4 & 4.9 \\ 
Perplexity & 1 & 1.2 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Treatment and Management - Student} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Google & 52 & 64.2 \\ 
Xai & 15 & 18.5 \\ 
Openai & 6 & 7.4 \\ 
Anthropic & 4 & 4.9 \\ 
Perplexity & 3 & 3.7 \\ 
Deepseek & 1 & 1.2 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{verbatim}
Contingency table dimensions: 1 6 
\end{verbatim}

\begin{verbatim}
      anthropic deepseek google openai perplexity xai
human        22        9    131     35         12  91
\end{verbatim}

\begin{verbatim}
Warning: Fisher's exact test requires at least 2x2 table. Skipping.
\end{verbatim}

\begin{table}
\caption*{
{\large Statistical Significance Tests for Model Preferences\textsuperscript{\textit{1}}}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}llll}
\toprule
Statistical Test & Test Statistic & P-value & Interpretation \\ 
\midrule\addlinespace[2.5pt]
Overall preference distribution & χ² = 247.52 & <0.001 & Significant \\ 
Preferences differ by rater type & χ² = 247.52 & <0.001 & Significant \\ 
Google vs. equal preference & Binomial p = 0.0000 & <0.001 & Significantly preferred \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\textsuperscript{\textit{1}}Tests whether observed preferences differ significantly from chance\\
\end{minipage}
\end{table}

\subsection{1.3 Overall Performance by
Feature}\label{overall-performance-by-feature}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/calc-overall-feature-performance-1.pdf}}

\subsection{1.4 Per-Rater Summary
Statistics}\label{per-rater-summary-statistics}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/barplot-per-rater-stats1-1.pdf}}

\begin{longtable}[t]{lllrr}
\caption{Table 2. Individual rater summary statistics}\\
\toprule
Rater & Type & Mean ± SD & Median & N\\
\midrule
\cellcolor{gray!10}{OpenAI GPT-4o} & \cellcolor{gray!10}{Auto-grader} & \cellcolor{gray!10}{4.79 ± 0.46} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{2700}\\
Gemini 2.0 Flash & Auto-grader & 4.72 ± 0.46 & 5 & 2700\\
\cellcolor{gray!10}{Gemini 2.5 Pro} & \cellcolor{gray!10}{Auto-grader} & \cellcolor{gray!10}{4.65 ± 0.57} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{2700}\\
Anthropic Sonnet 3.5 & Auto-grader & 4.61 ± 0.62 & 5 & 2700\\
\cellcolor{gray!10}{Anthropic Sonnet 4} & \cellcolor{gray!10}{Auto-grader} & \cellcolor{gray!10}{4.51 ± 0.65} & \cellcolor{gray!10}{5} & \cellcolor{gray!10}{2700}\\
\addlinespace
OpenAI GPT-4o (Stricter) & Auto-grader & 4.17 ± 0.60 & 4 & 2700\\
\cellcolor{gray!10}{Expert 1} & \cellcolor{gray!10}{Expert} & \cellcolor{gray!10}{4.17 ± 0.79} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{2700}\\
Expert 2 & Expert & 3.81 ± 0.83 & 4 & 2700\\
\cellcolor{gray!10}{Expert 3} & \cellcolor{gray!10}{Expert} & \cellcolor{gray!10}{3.39 ± 1.00} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{2700}\\
Student 1 & Student & 4.41 ± 0.70 & 5 & 2700\\
\addlinespace
\cellcolor{gray!10}{Student 2} & \cellcolor{gray!10}{Student} & \cellcolor{gray!10}{4.02 ± 0.89} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{2700}\\
Student 3 & Student & 3.87 ± 0.93 & 4 & 2700\\
\bottomrule
\end{longtable}

\section{2. Feature-Specific Performance
Analysis}\label{feature-specific-performance-analysis}

\subsection{2.1 Model Performance by
Feature}\label{model-performance-by-feature}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/model-feature-heatmap-1.pdf}}

\begin{verbatim}
\begin{landscape}
\end{verbatim}

\begin{table}
\caption*{
{\large Mean Feature Ratings (95\% CI) by Model}
} 
\fontsize{6.8pt}{8.1pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|llllll}
\toprule
 & Anthropic & DeepSeek & Google & OpenAI & Perplexity & XAI \\ 
\midrule\addlinespace[2.5pt]
Appropriateness & 4.36 (4.29–4.43) & 4.38 (4.32–4.44) & 4.76 (4.72–4.80) & 4.43 (4.36–4.49) & 4.21 (4.14–4.28) & 4.58 (4.54–4.63) \\ 
Comprehensibility & 4.14 (4.06–4.23) & 4.16 (4.08–4.23) & 4.58 (4.53–4.62) & 4.37 (4.30–4.43) & 4.03 (3.96–4.11) & 4.50 (4.45–4.55) \\ 
Completeness & 4.11 (4.04–4.19) & 4.26 (4.19–4.33) & 4.82 (4.78–4.85) & 4.37 (4.30–4.43) & 4.00 (3.93–4.08) & 4.59 (4.54–4.64) \\ 
Conciseness & 4.05 (3.99–4.11) & 3.98 (3.92–4.04) & 3.62 (3.56–3.68) & 3.76 (3.70–3.81) & 3.78 (3.72–3.84) & 3.65 (3.60–3.71) \\ 
Confabulation Avoidance & 4.42 (4.36–4.49) & 4.40 (4.33–4.47) & 4.71 (4.66–4.76) & 4.46 (4.40–4.53) & 4.34 (4.28–4.41) & 4.58 (4.52–4.63) \\ 
Readability & 4.31 (4.24–4.38) & 4.32 (4.25–4.38) & 4.42 (4.36–4.48) & 4.29 (4.23–4.36) & 4.02 (3.94–4.10) & 4.37 (4.31–4.42) \\ 
Educational Value & 4.10 (4.02–4.17) & 4.20 (4.12–4.27) & 4.81 (4.77–4.85) & 4.33 (4.26–4.40) & 4.03 (3.96–4.11) & 4.56 (4.51–4.61) \\ 
Actionability & 4.08 (4.00–4.15) & 4.20 (4.13–4.27) & 4.67 (4.62–4.71) & 4.24 (4.18–4.31) & 3.88 (3.80–3.95) & 4.51 (4.46–4.56) \\ 
Tone/Empathy & 3.77 (3.70–3.84) & 3.89 (3.83–3.96) & 4.55 (4.50–4.59) & 4.08 (4.02–4.14) & 3.70 (3.64–3.76) & 4.33 (4.28–4.38) \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{verbatim}
\end{landscape}
\end{verbatim}

\begin{table}
\caption*{
{\large Best- and Worst-Rated Features by Model}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}cll}
\toprule
Model & Highest & Lowest \\ 
\midrule\addlinespace[2.5pt]
Anthropic & Confabulation Avoidance (4.42 [4.36–4.49]) & Tone/Empathy (3.77 [3.70–3.84]) \\ 
DeepSeek & Confabulation Avoidance (4.40 [4.33–4.47]) & Tone/Empathy (3.89 [3.83–3.96]) \\ 
Google & Completeness (4.82 [4.78–4.85]) & Conciseness (3.62 [3.56–3.68]) \\ 
OpenAI & Confabulation Avoidance (4.46 [4.40–4.53]) & Conciseness (3.76 [3.70–3.81]) \\ 
Perplexity & Confabulation Avoidance (4.34 [4.28–4.41]) & Tone/Empathy (3.70 [3.64–3.76]) \\ 
XAI & Completeness (4.59 [4.54–4.64]) & Conciseness (3.65 [3.60–3.71]) \\ 
\bottomrule
\end{tabular*}
\end{table}

\subsubsection{Interpretation}\label{interpretation}

\begin{itemize}
\item
  \textbf{Anthropic}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Confabulation Avoidance} (mean = 4.42).
  \item
    Lowest: \textbf{Tone/Empathy} (mean = 3.77).
  \end{itemize}
\item
  \textbf{DeepSeek}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Confabulation Avoidance} (mean = 4.40).
  \item
    Lowest: \textbf{Tone/Empathy} (mean = 3.89).
  \end{itemize}
\item
  \textbf{Google}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Completeness} (mean = 4.82).
  \item
    Lowest: \textbf{Conciseness} (mean = 3.62).
  \end{itemize}
\item
  \textbf{OpenAI}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Confabulation Avoidance} (mean = 4.46).
  \item
    Lowest: \textbf{Conciseness} (mean = 3.76).
  \end{itemize}
\item
  \textbf{Perplexity}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Confabulation Avoidance} (mean = 4.34).
  \item
    Lowest: \textbf{Tone/Empathy} (mean = 3.70).
  \end{itemize}
\item
  \textbf{XAI}

  \begin{itemize}
  \tightlist
  \item
    Highest: \textbf{Completeness} (mean = 4.59).
  \item
    Lowest: \textbf{Conciseness} (mean = 3.65).
  \end{itemize}
\end{itemize}

\begin{quote}
Clinicians can use these highlights---each model's strongest and weakest
feature---to decide which system best fits their specific priorities.
\end{quote}

\subsection{2.2 Rater Type Comparison by
Feature}\label{rater-type-comparison-by-feature}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/rater-type-feature-1.pdf}}

\section{3. Inter-Rater Reliability
Analysis}\label{inter-rater-reliability-analysis}

\subsection{3.1 Within-Group
Reliability}\label{within-group-reliability}

We compute the single‐measure, absolute‐agreement ICC (ICC(A,1)) for
each rater group (Students, Experts, Auto-graders) using a two-way
random‐effects model. First we show ICC for all rating features
combined:

\begin{verbatim}
 Single Score Intraclass Correlation

   Model: twoway 
   Type : agreement 

   Subjects = 2700 
     Raters = 3 
   ICC(A,1) = 0.371

 F-Test, H0: r0 = 0 ; H1: r0 > 0 
F(2699,173) = 3.09 , p = 2.11e-18 

 95%-Confidence Interval for ICC Population Values:
  0.291 < ICC < 0.441
\end{verbatim}

\begin{verbatim}
 Single Score Intraclass Correlation

   Model: twoway 
   Type : agreement 

   Subjects = 2700 
     Raters = 3 
   ICC(A,1) = 0.126

 F-Test, H0: r0 = 0 ; H1: r0 > 0 
F(2699,449) = 1.53 , p = 1.04e-08 

 95%-Confidence Interval for ICC Population Values:
  0.081 < ICC < 0.171
\end{verbatim}

\begin{verbatim}
 Single Score Intraclass Correlation

   Model: twoway 
   Type : agreement 

   Subjects = 2700 
     Raters = 6 
   ICC(A,1) = 0.492

 F-Test, H0: r0 = 0 ; H1: r0 > 0 
F(2699,95.3) = 8.83 , p = 2.44e-28 

 95%-Confidence Interval for ICC Population Values:
  0.404 < ICC < 0.567
\end{verbatim}

\begin{table}
\caption*{
{\large Within‐Group ICC(A,1) Results}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrll}
\toprule
Rater Group & ICC(A,1) & (95\% CI) & Interpretation \\ 
\midrule\addlinespace[2.5pt]
Students & 0.371 & (0.291–0.441) & Poor agreement \\ 
Experts & 0.126 & (0.081–0.171) & Poor agreement \\ 
Auto-graders & 0.492 & (0.404–0.567) & Poor agreement \\ 
\bottomrule
\end{tabular*}
\end{table}

\subsection{3.1. Within-Group Reliability (Cont'd for each feature
category)}\label{within-group-reliability-contd-for-each-feature-category}

\begin{table}
\caption*{
{\large Feature-Wise ICC(A,1) by Rater Group}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}l|rl}
\toprule
 & ICC(A,1) & (95\% CI) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Auto-grader} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Appropriateness & 0.167 & (0.087–0.252) \\ 
Comprehensibility & 0.203 & (0.111–0.298) \\ 
Completeness & 0.399 & (0.328–0.470) \\ 
Conciseness & 0.153 & (0.075–0.237) \\ 
Confabulation Avoidance & 0.286 & (0.224–0.350) \\ 
Readability & 0.148 & (0.067–0.238) \\ 
Educational Value & 0.352 & (0.282–0.423) \\ 
Actionability & 0.386 & (0.286–0.480) \\ 
Tone/Empathy & 0.282 & (0.182–0.380) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Expert} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Appropriateness & 0.150 & (0.060–0.243) \\ 
Comprehensibility & 0.211 & (0.130–0.295) \\ 
Completeness & 0.276 & (0.167–0.380) \\ 
Conciseness & -0.170 & (-0.227–-0.104) \\ 
Confabulation Avoidance & 0.022 & (-0.016–0.066) \\ 
Readability & -0.011 & (-0.062–0.046) \\ 
Educational Value & 0.167 & (0.083–0.253) \\ 
Actionability & 0.193 & (0.111–0.277) \\ 
Tone/Empathy & 0.260 & (0.168–0.350) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Student} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Appropriateness & 0.352 & (0.275–0.429) \\ 
Comprehensibility & 0.327 & (0.219–0.427) \\ 
Completeness & 0.464 & (0.356–0.558) \\ 
Conciseness & 0.287 & (0.205–0.369) \\ 
Confabulation Avoidance & 0.192 & (0.020–0.357) \\ 
Readability & 0.336 & (0.213–0.447) \\ 
Educational Value & 0.559 & (0.468–0.638) \\ 
Actionability & 0.366 & (0.234–0.482) \\ 
Tone/Empathy & 0.414 & (0.273–0.531) \\ 
\bottomrule
\end{tabular*}
\end{table}

\subsubsection{Interpretation}\label{interpretation-1}

\textbf{coming soon}

\subsection{3.2 Between-Group
Reliability}\label{between-group-reliability}

We'll use \textbf{ICC(2,k)} (two‐way random, absolute‐agreement,
\emph{average}‐measure) to ask how reliable the \emph{mean} rating is
when we pool different sets of raters:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{All 12 raters} (3 Students + 3 Experts + 6 Auto-graders)\\
\item
  \textbf{Students + Experts} (6 human raters)\\
\item
  \textbf{Experts + Auto-graders} (9 raters)
\end{enumerate}

\begin{table}
\caption*{
{\large Between‐Group ICC(2,k) by Feature}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}l|lll}
\toprule
 & All 12 Raters & Students + Experts & Experts + Auto‐graders \\ 
\midrule\addlinespace[2.5pt]
Appropriateness & 0.671 (0.551–0.755) & 0.658 (0.541–0.741) & 0.499 (0.275–0.646) \\ 
Comprehensibility & 0.655 (0.526–0.745) & 0.685 (0.596–0.753) & 0.489 (0.268–0.635) \\ 
Completeness & 0.783 (0.676–0.848) & 0.779 (0.691–0.837) & 0.655 (0.447–0.773) \\ 
Conciseness & 0.504 (0.376–0.606) & 0.198 (0.026–0.344) & 0.236 (0.071–0.376) \\ 
Confabulation Avoidance & 0.559 (0.352–0.692) & 0.437 (0.142–0.619) & 0.418 (0.148–0.597) \\ 
Readability & 0.521 (0.346–0.644) & 0.548 (0.410–0.650) & 0.291 (0.038–0.476) \\ 
Educational Value & 0.733 (0.603–0.813) & 0.763 (0.694–0.816) & 0.572 (0.345–0.709) \\ 
Actionability & 0.803 (0.732–0.852) & 0.715 (0.621–0.784) & 0.716 (0.586–0.799) \\ 
Tone/Empathy & 0.787 (0.705–0.843) & 0.767 (0.690–0.822) & 0.680 (0.526–0.775) \\ 
\bottomrule
\end{tabular*}
\end{table}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/plot-betweengrp-styled-1.pdf}}

\subsubsection{Comments on Usefulness}\label{comments-on-usefulness}

\begin{itemize}
\tightlist
\item
  \textbf{Average-measure ICC(2,k)} tells you how reliable the
  \emph{mean} of \emph{k} raters is, which naturally increases as you
  add more raters (since random error averages out).
\item
  As expected, pooling \textbf{all 12} yields the highest reliability
  for every feature.
\item
  The \textbf{Students + Experts} panel (6 human raters) shows
  noticeably lower ICCs than the full panel, highlighting the value of
  adding automated scores.
\item
  Combining \textbf{Experts + Auto-graders} (9 raters) recovers much of
  the full-panel reliability, suggesting auto-graders complement expert
  raters well.
\end{itemize}

\begin{quote}
\textbf{Caveat:} Because our \emph{single-measure} (ICC(2,1))
within-group reliabilities were often only \emph{fair} (≤0.5), these
average-measure ICCs should be interpreted with caution. You're
essentially demonstrating that \emph{more} raters produce more reliable
\emph{means}---a well-known statistical effect---rather than uncovering
a deep alignment between groups. If you wanted to know \emph{how} well
human consensus matches auto-grader consensus \emph{per se}, you'd
instead compute ICC(2,1) on the two \textbf{group means} (one ``human''
mean vs.~one ``auto'' mean), but that only makes sense if each group
mean is itself reliable (which, here, is marginal for some features).
\end{quote}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{4. Model Performance
Comparison}\label{model-performance-comparison}

\subsection{4.1 Linear Mixed-Effects
Models}\label{linear-mixed-effects-models}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/Fit-lmm-all-features-1.pdf}}

\begin{table}
\caption*{
{\large Table 4. Likelihood‐Ratio Tests for Model Effects}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
Feature & χ² & df & p-value & Significant \\ 
\midrule\addlinespace[2.5pt]
Appropriateness & 296.47 & 5 & <0.001 & *** \\ 
Comprehensibility & 332.71 & 5 & <0.001 & *** \\ 
Completeness & 698.07 & 5 & <0.001 & *** \\ 
Conciseness & 227.21 & 5 & <0.001 & *** \\ 
Confabulation Avoidance & 210.47 & 5 & <0.001 & *** \\ 
Readability & 137.34 & 5 & <0.001 & *** \\ 
Educational Value & 668.49 & 5 & <0.001 & *** \\ 
Actionability & 576.41 & 5 & <0.001 & *** \\ 
Tone/Empathy & 852.74 & 5 & <0.001 & *** \\ 
\bottomrule
\end{tabular*}
\end{table}

\begingroup
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{longtable*}{cr}
\caption*{
{\large Table 5. Estimated Marginal Means for Significant Features}
} \\ 
\toprule
Model & Estimated Mean (95\% CI) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Actionability} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.07 (3.83-4.32) \\ 
deepseek & 4.20 (3.96-4.44) \\ 
google & 4.67 (4.42-4.91) \\ 
openai & 4.24 (4.00-4.49) \\ 
perplexity & 3.88 (3.63-4.12) \\ 
xai & 4.51 (4.27-4.76) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Appropriateness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.36 (4.11-4.61) \\ 
deepseek & 4.38 (4.13-4.63) \\ 
google & 4.76 (4.51-5.01) \\ 
openai & 4.43 (4.18-4.67) \\ 
perplexity & 4.21 (3.97-4.46) \\ 
xai & 4.58 (4.34-4.83) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Completeness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.11 (3.83-4.40) \\ 
deepseek & 4.26 (3.97-4.54) \\ 
google & 4.82 (4.53-5.10) \\ 
openai & 4.37 (4.08-4.65) \\ 
perplexity & 4.00 (3.72-4.29) \\ 
xai & 4.59 (4.30-4.88) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Comprehensibility} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.14 (3.87-4.42) \\ 
deepseek & 4.15 (3.88-4.43) \\ 
google & 4.57 (4.30-4.85) \\ 
openai & 4.36 (4.09-4.64) \\ 
perplexity & 4.03 (3.75-4.31) \\ 
xai & 4.50 (4.23-4.78) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Conciseness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.05 (3.85-4.26) \\ 
deepseek & 3.98 (3.77-4.19) \\ 
google & 3.62 (3.41-3.82) \\ 
openai & 3.76 (3.55-3.96) \\ 
perplexity & 3.78 (3.58-3.99) \\ 
xai & 3.66 (3.45-3.86) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Confabulation Avoidance} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.42 (4.10-4.75) \\ 
deepseek & 4.40 (4.08-4.72) \\ 
google & 4.71 (4.39-5.03) \\ 
openai & 4.46 (4.14-4.78) \\ 
perplexity & 4.34 (4.02-4.67) \\ 
xai & 4.58 (4.26-4.90) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Educational Value} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.10 (3.79-4.40) \\ 
deepseek & 4.20 (3.89-4.50) \\ 
google & 4.81 (4.51-5.11) \\ 
openai & 4.33 (4.03-4.64) \\ 
perplexity & 4.03 (3.73-4.34) \\ 
xai & 4.56 (4.26-4.86) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Readability} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 4.31 (4.02-4.61) \\ 
deepseek & 4.31 (4.02-4.61) \\ 
google & 4.42 (4.12-4.72) \\ 
openai & 4.29 (4.00-4.59) \\ 
perplexity & 4.02 (3.72-4.32) \\ 
xai & 4.37 (4.07-4.66) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{2}{l}{Tone/Empathy} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
anthropic & 3.77 (3.52-4.01) \\ 
deepseek & 3.89 (3.65-4.14) \\ 
google & 4.55 (4.30-4.79) \\ 
openai & 4.08 (3.84-4.33) \\ 
perplexity & 3.70 (3.46-3.94) \\ 
xai & 4.33 (4.09-4.58) \\ 
\bottomrule
\end{longtable*}
\endgroup

\subsection{4.2 Rater Type Effects}\label{rater-type-effects}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/viz-rater-type-effects-1.pdf}}

\begin{table}
\caption*{
{\large Pairwise Comparisons by Feature}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}l|rrrl}
\toprule
 & Estimate & Std. Error & Adjusted p-value & Significance \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Appropriateness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.739 & 0.200 & 0.001 & *** \\ 
(Auto-grader) - Student & 0.409 & 0.200 & 0.103 & ns \\ 
Expert - Student & -0.330 & 0.231 & 0.327 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Comprehensibility} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.887 & 0.194 & 0.000 & *** \\ 
(Auto-grader) - Student & 0.619 & 0.194 & 0.004 & ** \\ 
Expert - Student & -0.268 & 0.224 & 0.456 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Completeness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 1.041 & 0.151 & 0.000 & *** \\ 
(Auto-grader) - Student & 0.638 & 0.151 & 0.000 & *** \\ 
Expert - Student & -0.402 & 0.174 & 0.055 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Conciseness} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.069 & 0.196 & 0.933 & ns \\ 
(Auto-grader) - Student & -0.469 & 0.196 & 0.044 & * \\ 
Expert - Student & -0.539 & 0.227 & 0.046 & * \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Confabulation Avoidance} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.905 & 0.270 & 0.002 & ** \\ 
(Auto-grader) - Student & 0.696 & 0.270 & 0.027 & * \\ 
Expert - Student & -0.209 & 0.312 & 0.781 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Readability} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.983 & 0.213 & 0.000 & *** \\ 
(Auto-grader) - Student & 0.602 & 0.213 & 0.013 & * \\ 
Expert - Student & -0.381 & 0.246 & 0.269 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Educational Value} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 1.026 & 0.152 & 0.000 & *** \\ 
(Auto-grader) - Student & 0.882 & 0.152 & 0.000 & *** \\ 
Expert - Student & -0.144 & 0.175 & 0.688 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Actionability} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.708 & 0.189 & 0.001 & *** \\ 
(Auto-grader) - Student & 0.407 & 0.189 & 0.080 & ns \\ 
Expert - Student & -0.301 & 0.218 & 0.352 & ns \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{l}{Tone/Empathy} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
(Auto-grader) - Expert & 0.731 & 0.189 & 0.000 & *** \\ 
(Auto-grader) - Student & 0.486 & 0.189 & 0.027 & * \\ 
Expert - Student & -0.244 & 0.218 & 0.500 & ns \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{5. Multivariate Analysis}\label{multivariate-analysis}

\subsection{5.1 Principal Component
Analysis}\label{principal-component-analysis}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/scree-plot-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/biplot-models-features-1.pdf}}

\subsubsection{Interpretation of PCA
Biplot}\label{interpretation-of-pca-biplot}

This PCA biplot summarizes the relationships between different language
models and human evaluation features using the first two principal
components.

The first principal component (\textbf{PC1}) explains 88.8\% of the
total variance, while the second component (\textbf{PC2}) explains
9.8\%. Together, they account for 98.6\% of the overall variance,
indicating that most of the meaningful differences between models are
captured in this 2D space.

\textbf{Feature Contributions}

The blue arrows represent evaluation features, where: - The
\textbf{direction} indicates the orientation of increasing values for
that feature. - The \textbf{length} reflects the strength of that
feature's contribution to the variance captured by PC1 and PC2.

For example: - Features such as \textbf{Completeness} and
\textbf{Conciseness} contribute most to PC1 and PC2, respectively.

\textbf{Model Comparison}

The yellow dots represent different language models. Models located near
a feature arrow likely score highly on that feature. Conversely, models
opposite the direction of a feature vector tend to score lower on it.

\begin{itemize}
\tightlist
\item
  Models like \textbf{perplexity} are positioned strongly along PC1,
  indicating high alignment with features like \textbf{Completeness}.
\item
  In contrast, \textbf{google} scores lower on those same features.
\end{itemize}

\textbf{Summary}

This plot helps visualize how models differ in their qualitative
strengths. For example: - Models positioned in the direction of
\textbf{Conciseness} and \textbf{Readability} likely produce more
compact and easier-to-read outputs. - Those aligned with
\textbf{Comprehensibility}, \textbf{Actionability}, and
\textbf{Educational Value} may offer more informative or helpful
responses, even if they are less concise.

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/feature-loadings-plot-no-models-1.pdf}}

The above plot simply shows how each feature contributes to PCs.

This feature loadings plot specifically emphasizes: - Which features
contribute most to PC1 and PC2. - How features relate to each other
(e.g., clusters or oppositions). - Avoids clutter from model points ---
it's cleaner for purely feature-based interpretation.

\textbf{Interpretation:}

\begin{itemize}
\tightlist
\item
  Conciseness and Readability are the strongest contributors, pulling in
  opposite directions along PC1 and PC2 respectively.
\item
  Most other features (e.g., Actionability, Completeness, Educational
  Value) cluster closely together with small loadings, contributing
  moderately and similarly to PC1.
\end{itemize}

\textbf{The Core Trade-off}

The analysis reveals a fundamental tension in AI model design:
\textbf{Comprehensiveness vs.~Conciseness} - PC1 (88.8\% of variance)
essentially captures this trade-off. Models can either be thorough,
helpful, and comprehensive OR concise and to-the-point, but excelling at
both simultaneously appears challenging.

This makes intuitive sense - providing complete, educational, empathetic
responses often requires more words and detail, which inherently
conflicts with being concise.

\begin{longtable}[t]{llll}
\caption{Table 6. Feature loadings on first two principal components}\\
\toprule
 & Feature & PC1 & PC2\\
\midrule
\cellcolor{gray!10}{Completeness} & \cellcolor{gray!10}{Completeness} & \cellcolor{gray!10}{-0.353} & \cellcolor{gray!10}{-0.004}\\
Tone/Empathy & Tone/Empathy & -0.352 & -0.089\\
\cellcolor{gray!10}{Educational Value} & \cellcolor{gray!10}{Educational Value} & \cellcolor{gray!10}{-0.352} & \cellcolor{gray!10}{-0.079}\\
Actionability & Actionability & -0.350 & 0.121\\
\cellcolor{gray!10}{Appropriateness} & \cellcolor{gray!10}{Appropriateness} & \cellcolor{gray!10}{-0.350} & \cellcolor{gray!10}{0.111}\\
\addlinespace
Comprehensibility & Comprehensibility & -0.347 & -0.040\\
\cellcolor{gray!10}{Confabulation Avoidance} & \cellcolor{gray!10}{Confabulation Avoidance} & \cellcolor{gray!10}{-0.346} & \cellcolor{gray!10}{0.001}\\
Readability & Readability & -0.278 & 0.650\\
\cellcolor{gray!10}{Conciseness} & \cellcolor{gray!10}{Conciseness} & \cellcolor{gray!10}{0.256} & \cellcolor{gray!10}{0.732}\\
\bottomrule
\end{longtable}

\subsection{5.2 Cluster Analysis of
Models}\label{cluster-analysis-of-models}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/dendrogram-plot1-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/dendrogram-plot-fviz-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/kmeans-clusters-plot-1.pdf}}

\subsection{5.3 Auto-grader vs Human Consensus
Analysis}\label{auto-grader-vs-human-consensus-analysis}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/auto-human-correlation-heatmap-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/auto-grader-performance-metrics-vs-human-consensus-1.pdf}}

\begin{table}
\caption*{
{\large Table 7. Auto-grader performance metrics compared to human consensus}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrr}
\toprule
Auto-grader & Root Mean Square Error & Mean Absolute Error & Bias & Correlation \\ 
\midrule\addlinespace[2.5pt]
Anthropic Sonnet 3.5 & 0.962 & 0.807 & 0.667 & 0.303 \\ 
Anthropic Sonnet 4 & 0.879 & 0.727 & 0.564 & 0.378 \\ 
Gemini 2.0 Flash & 0.981 & 0.823 & 0.778 & 0.316 \\ 
Gemini 2.5 Pro & 0.920 & 0.776 & 0.707 & 0.453 \\ 
OpenAI GPT-4o & 1.051 & 0.893 & 0.841 & 0.230 \\ 
OpenAI GPT-4o (Stricter) & 0.729 & 0.586 & 0.229 & 0.276 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{6. Summary and Key Findings}\label{summary-and-key-findings}

\subsection{6.1 Overall Performance
Summary}\label{overall-performance-summary}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/unnamed-chunk-2-1.pdf}}

\subsection{6.2 Key Statistical
Findings}\label{key-statistical-findings}

\begin{table}
\caption*{
{\large Table 8. Summary of Key Statistical Findings}
} 
\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}lll}
\toprule
Metric & Finding & Details \\ 
\midrule\addlinespace[2.5pt]
Best Performing Model & google & Mean rating = 4.55 \\ 
Most Reliable Feature & Confabulation Avoidance & Mean rating = 4.49 \\ 
Least Reliable Feature & Conciseness & Mean rating = 3.81 \\ 
Human-Auto Agreement & r = 0.326 & Average across all auto-graders \\ 
Features with Significant Model Differences & Appropriateness, Comprehensibility, Completeness, Conciseness, Confabulation Avoidance, Readability, Educational Value, Actionability, Tone/Empathy & Appropriateness, Comprehensibility, Completeness, Conciseness, Confabulation Avoidance, Readability, Educational Value, Actionability, Tone/Empathy \\ 
\bottomrule
\end{tabular*}
\end{table}

\section{7. Supplementary Materials}\label{supplementary-materials}

\subsection{7.1 Model Diagnostics}\label{model-diagnostics}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/model-diagnostics-lmm-samplefeature-appropriateness-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/qq-plot-random-effects-1.pdf}}

\pandocbounded{\includegraphics[keepaspectratio]{stats_analysis_files/figure-pdf/qq-plot-random-effects-raters-1.pdf}}

\section{References}\label{references}

\begin{verbatim}

Analysis completed successfully. All figures saved to 'figures/' directory.
\end{verbatim}




\end{document}
